
CREAT TABLE
	 CARS(VIN INT VARCHAR (50),
		MANUFACTURER VARCHAR (50),
		MODEL VARCHAR (50),
		YEAR INT,
		COLOR_OF_THE_CAR VARCHAR (50));

CREAT TABLE
	 CUSTOMERS(
		CUSTOMER_ID VARCHAR (50), 
		NAME VARCHAR (50),
		PHONE_NUMBER VARCHAR (50),
		EMAIL VARCHAR (50),
		ADDRESS VARCHAR (50),
		CITY VARCHAR (50),
		STATE_PROVINCE VARCHAR (50),
		COUNTRY VARCHAR (50),
		ZIP INT);

CREAT TABLE
	 SALESPERSONS(
		STAFF_ID VARCHAR (50),
		NAME VARCHAR (50),
		STORES VARCHAR (50));

CREAT TABLE
	 INVOICES(
		INVOICE_NUMBER VARCHAR (50),
		DATE DATE,
		CAR VARCHAR (50),
		CUSTOMER VARCHAR (50),
		SALESPERSON VARCHAR (50));
