DROP SCHEMA IF EXISTS lab_mysql;
CREATE DATABASE lab_mysql;
USE lab_mysql;




CREATE TABLE Cars (
  Cars_ID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  VIN VARCHAR(45) NOT NULL,
  Manufacturer VARCHAR(45) NOT NULL,
  Model VARCHAR(45) NOT NULL,
  relace_year YEAR DEFAULT NULL,
  Color VARCHAR(45) NOT NULL,
  PRIMARY KEY  (Cars_ID)
  );



CREATE TABLE Customers (
  Customers_ID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  Custumer_ID2 SMALLINT NOT NULL,
  Name_Customers VARCHAR(45) NOT NULL,
  Phone VARCHAR(20) NOT NULL,
  Email VARCHAR(50) DEFAULT NULL,
  Address VARCHAR(50) NOT NULL,
  City VARCHAR(45) NOT NULL,
  State_Province VARCHAR(45) NOT NULL,
  Country VARCHAR(45) NOT NULL,
  Postal VARCHAR(10) DEFAULT NULL,
  PRIMARY KEY  (Customers_ID ));
  
  CREATE TABLE Salespersons (
  Salespersons_ID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  Staff_ID SMALLINT NOT NULL,
  Name_Sales VARCHAR(45) NOT NULL,
  Store VARCHAR(20) NOT NULL,
  PRIMARY KEY  (Salespersons_ID));
  
  CREATE TABLE Invoices (
  Invoices_ID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  Invoices_Number INT NOT NULL,
  Date_Invoices VARCHAR(45) NOT NULL,
  Cars_ID SMALLINT UNSIGNED NOT NULL,
  Customers_ID SMALLINT UNSIGNED NOT NULL,
  Salespersons_ID SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY  (Invoices_ID),
  KEY idx_fk_Cars_ID (Cars_ID),
  CONSTRAINT `fk_Cars_ID` FOREIGN KEY (Cars_ID) REFERENCES Cars (Cars_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
  
  KEY idx_fk_Salespersons_ID (Salespersons_ID),
  CONSTRAINT `fk_Salespersons_ID` FOREIGN KEY (Salespersons_ID) REFERENCES Salespersons (Salespersons_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
  
  KEY idx_fk_Customers_ID (Customers_ID),
  CONSTRAINT `fk_Customers_ID` FOREIGN KEY (Customers_ID) REFERENCES Customers (Customers_ID) ON DELETE RESTRICT ON UPDATE CASCADE
  );